### PR TITLE
Added local CSS support

### PR DESCRIPTION
**Pull request by benlongmire**
- Changed repathImages to repathLocalFiles and included repathing of `<link>` elements

### CODE REVIEW

**Comment by benlongmire** [comment]
The only thing I've found that doesn't work is updating a CSS file doesn't cause a re-render. I'll look into possibility of watching for changes of local CSS files.

**Comment by johnknoop** [comment]
Hi and thanks for this contribution. I'm gonna need to test this locally before I merge it. Give me a couple of days. /john

**Comment by benlongmire** [comment]
No worries, John.

I have added another commit which includes CSS cache clearing.

I also have removed some code which I think was redundant i.e the context file was being explicitly watched for changes, however the extension itself was already set up to watch for changes in all files in the workspace.

**Comment by johnknoop** [comment]
Everything seems to work as far as I can tell. Thanks for the contribution, and nice finding about the superfluous watching of context files!

**Comment by benlongmire** [comment]
No worries, glad to help.

**Pull request merged**
